<?php

namespace MailPoetVendor;

if (!defined('ABSPATH')) exit;


// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInit8d299965b35b9f25798c766beb83a04f::getLoader();
